# Generated by Django 3.2.6 on 2021-11-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='bookname',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='bookID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookMng.book'),
        ),
    ]
