# Generated by Django 3.2.6 on 2021-11-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0008_auto_20211113_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(blank=True, to='bookMng.Book'),
        ),
    ]
