# Generated by Django 3.2.6 on 2021-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0013_auto_20211113_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='identification',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wishlistbook',
            name='compareID',
            field=models.CharField(default='', max_length=200),
        ),
    ]
